### ISSUE TITLE
Fixed footer on data table

### ISSUE THREAD

**Issue by veliozguryildiz** [PitcherAG/pitcher-vue-sdk#107]
Hi all, 

I need to make the footer of data table sticky so that only body will be scrollable.

I believe a solution to this does not exist within data table component.

Can someone add it, or I can work on it as well.

**Comment by elibolonur** [comment]
With the current state of the component, it does not make any sense to add a footer component that is sticky. Look and feel after making the table footer sticky, depends on how the component is used in the DOM tree. Please try to achieve what you are doing by overriding css classes of table and its container.
