### ISSUE TITLE
setLanguage fetch usage

### ISSUE THREAD

**Issue by elibolonur** [PitcherAG/pitcher-vue-sdk#45]
Fetching the translation files with fetch() function probably creating an issue on windows env.
Lets check the alternatives (axios etc.) and see if it works properly.

**Comment by digi604** [comment]
fixed with fetch pollyfill but maybe add the polyfill to sdk or project template

https://github.com/github/fetch 

also maybe lazy loading it:

https://itnext.io/lazy-loading-polyfills-4b85c4951e73

**Comment by elibolonur** [comment]
fixed in #61
