### ISSUE TITLE
add gettext tests, docs and npm scripts for sdk

### ISSUE THREAD

**Issue by digi604** [PitcherAG/pitcher-vue-sdk#62]

**Comment by elibolonur** [comment]
is this completed? @torfeld6

**Comment by elibolonur** [comment]
also getting error in template project:

```i18n.js?ec15:21 Uncaught (in promise) Error: invalid language: en-US``` @torfeld6

**Comment by elibolonur** [comment]
fixed in 1.3.10

**Comment by elibolonur** [comment]
Awaiting docs update

**Comment by elibolonur** [comment]
Can we complete this soon @torfeld6

**Comment by torfeld6** [comment]
@digi604 use google.json by GOOGLE_APPLICATION_CREDENTIALS=google.json

**Comment by torfeld6** [comment]
add @pitcher/easy-gettext to package.json
