### ISSUE TITLE
DataTable Extra Features

### ISSUE THREAD

**Issue by veliozguryildiz** [PitcherAG/pitcher-vue-sdk#67]
- I need to inject a slot to the top of the table body. With the current setup, if I need to add body slot, then I need to change all of the body content.

- Right now, tooltip copies the text within "Title" attribute of the field. I need customizable tooltip texts.

**Comment by elibolonur** [comment]
To do:
- add prepend-tbody slot
- add append-tbody slot
- add prop for tooltip text

**Comment by elibolonur** [comment]
Slots & prop added to DataTable.

Will be published in 1.3.9

**Comment by elibolonur** [comment]
- add rowClick event
- check other events

**Comment by elibolonur** [comment]
rowClick event added

**Comment by elibolonur** [comment]
#71
