### ISSUE TITLE
Documentation update to show components visually

### ISSUE THREAD

**Issue by elibolonur** [PitcherAG/pitcher-vue-sdk#79]
Update documentation to show components visually. We might need to replace docsify with something else.

**Comment by elibolonur** [comment]
Storybook will be added, looping in @yasatbilgin

**Comment by digi604** [comment]
Is there any progress here? Otherwise i think @grzk has some experience with this?

**Comment by kouts** [comment]
This can be closed now as we transered the docs to Storybook.  https://github.com/PitcherAG/pitcher-vue-sdk/pull/111
