### ISSUE TITLE
langV = 'FR', but params.state.language.value = 'en'

### ISSUE THREAD

**Issue by veliozguryildiz** [PitcherAG/pitcher-vue-sdk#82]
Hi all,

After setting device language to French, I check params gathered through useParamsStore(), params.state.language.value returns 'en' while params.state.langV = 'FR'. Can you check?

Platorm is Windows

**Comment by digi604** [comment]
what is the value of: params.language.value?

**Comment by digi604** [comment]
we have the language getter for this

**Comment by torfeld6** [comment]
It's possible your Salesforce language is EN and your device language is FR. I believe in Patrick's getter, the Salesforce language takes preference over the device language. If you don't want to use Patrick's getter, use `state.langV` directly.

**Comment by torfeld6** [comment]
There you go: https://github.com/PitcherAG/pitcher-vue-sdk/blob/master/src/params.js#L36
We might change it to:
```
sfLanguage() {
            if (s.state.salesForceUser) {
                return s.state.salesForceUser.LanguageLocaleKey.split('_')[0].toLowerCase()
            }

            if (s.state.user) {
                return s.state.user.LanguageLocaleKey.split('_')[0].toLowerCase()
            }
},
deviceLanguage() {
            if (s.state.config) {
                const isoLocaleMap = {
                    AUSDE: 'de',
                    BI: 'id',
                    BR: 'pt',
                    BU: 'bg',
                    CAFR: 'fr',
                    CZ: 'cs',
                    DAN: 'da',
                    ESMX: 'es',
                    EST: 'et',
                    JP: 'ja',
                    LET: 'lv',
                    PO: 'pl',
                    PRT: 'pt',
                    SCH: 'zh-CN',
                    TCH: 'zh-TW',
                    UA: 'uk',
                    VN: 'vi'
                }

                if (isoLocaleMap[s.state.config.langV]) {
                    return isoLocaleMap[s.state.config.langV]
                } else {
                    return s.state.config.langV.toLowerCase()
                }
            }
}
```

**Comment by veliozguryildiz** [comment]
Oh, did not know that preference issue. For trial, changed already to state.langV but while pushing I believe I will use this preference guys. Thanks a lot!

**Comment by elibolonur** [comment]
Is this resolved? @torfeld6 @veliozguryildiz

**Comment by veliozguryildiz** [comment]
Yeah it is, for further references:

use language getter for SFDC language,
use state.langV for device language, since Joshua's commit is not yet published.

Thanks a lot.
