### ISSUE TITLE
Datatable new features

### ISSUE THREAD

**Issue by digi604** [PitcherAG/pitcher-vue-sdk#85]
add a new prop: groupBy or something and this will group rows based on this value. The groubBy value will also be the group name. 

Also create an advanced datatable with: search & filter capabilities built in.

**Comment by elibolonur** [comment]
To do:

- Grouping feature with group-by property,
- built-in filters

**Comment by elibolonur** [comment]
Also I have some concerns about including filters and search functionality inside the table, lets have a discussion about it later.

**Comment by elibolonur** [comment]
After the discussion the decision is to create a new component that combines, filters, datatable and search instead of adding these in to the current datatable.

Grouping feature will be added to current DataTable

**Comment by elibolonur** [comment]
fixed in #86
